spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/employee_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging:
  level:
    com.example.employee_management: DEBUG
    org.springframework: INFO
